import {test} from 'node:test';
import assert from 'node:assert/strict';
import {grow,advance,egg,archive,nextEgg,growthDay,CREATURES,choose} from '../dist/growth.mjs';
import {approve,initialState} from '../dist/domain.mjs';
const start=Date.parse('2026-10-01T00:00:00+09:00'),day=d=>start+(d-1)*86400000;
const grown=(points=10)=>({...grow(null,'cycle',start,'seed'),points,count:points/10});
test('legacy data hatches only with an approved chore, constant growth vs reward points',()=>{const s=initialState();s.accounts.kid={name:'子',points:100};const r={uid:'kid',type:'chore',itemId:'clean',day:'2026-10-01'};const n=approve(s,r,'r1',start);assert.equal(s.growth,undefined);assert.equal(n.growth.points,10);assert.equal(n.growth.stage,1);assert.equal(n.accounts.kid.points,130);assert.throws(()=>approve(n,r,'r1',start));assert.throws(()=>approve(n,r,'different',start));const reward=approve(n,{...r,type:'reward',itemId:'snack'},'r2',day(30));assert.deepEqual(reward.growth,n.growth);assert.equal(reward.accounts.kid.points,30)});
test('JST Day 1 and midnight, late approval is counted at approval time',()=>{const g=grown();assert.equal(growthDay(g,start),1);assert.equal(growthDay(g,start+86400000-1),1);assert.equal(growthDay(g,start+86400000),2);assert.equal(growthDay(egg('x')),0);const s=initialState();s.accounts.kid={points:0,name:'子'};const n=approve(s,{uid:'kid',type:'chore',itemId:'clean',day:'2020-01-01'},'late',day(30));assert.equal(n.growth.startedAt,day(30));assert.equal(growthDay(n.growth,day(30)),1)});
for(const [stage,d,points] of [[2,4,80],[3,7,150],[4,11,230]])test(`stage ${stage}: both day ${d} and ${points} points required`,()=>{assert.equal(advance(grown(points),day(d-1),'seed').stage,stage-1);assert.equal(advance(grown(points-10),day(d),'seed').stage,stage-1);assert.equal(advance(grown(points),day(d),'seed').stage,stage)});
test('Day 11 is not a deadline; no decay; multiple evolutions retain ordered lineage',()=>{const insufficient=advance(grown(210),day(11),'seed');assert.equal(insufficient.stage,3);const old=advance(insufficient,day(90),'seed');assert.equal(old.points,210);assert.equal(old.stage,3);const final=advance(grown(230),day(90),'seed');assert.deepEqual(final.path.map(p=>p.stage),[1,2,3,4]);for(let i=1;i<final.path.length;i++)assert.ok(CREATURES[final.path[i-1].character].next.includes(final.path[i].character));assert.equal(archive(final).days,90)});
test('retry and reload retain outcomes; seed can select both branches; weights injectable',()=>{const g=grown(230);assert.deepEqual(advance(g,day(21),'fixed'),advance(g,day(21),'fixed'));const final=advance(g,day(21),'fixed');assert.deepEqual(advance(JSON.parse(JSON.stringify(final)),day(60),'other'),final);assert.equal(new Set(Array.from({length:100},(_,i)=>choose(['a','b'],String(i),2))).size,2);assert.equal(choose(['a','b'],'x',2,x=>x==='a'?0:1),'b')});
test('next egg does not overwrite duplicate species records, no carryover or repeated reset',()=>{const g=advance(grown(240),day(22),'fixed'),record=archive(g),n=nextEgg(g,'new');assert.equal(n.points,0);assert.equal(n.startedAt,null);assert.throws(()=>nextEgg(n,'another'));assert.deepEqual(archive(g),record);assert.deepEqual(grow(g,'extra',day(30),'z'),g);const second=advance({...grow(n,'r',day(40),'fixed'),points:240,count:24},day(61),'fixed');assert.equal(second.character,g.character);assert.notEqual(archive(second).cycleId,record.cycleId)});
test('device migration keeps family-scoped growth and serialized histories',()=>{const state=initialState();state.accounts.old={name:'子',points:1};state.growth=advance(grown(230),day(21),'fixed');const history=[archive(state.growth)];state.accounts.new=state.accounts.old;delete state.accounts.old;const restored=JSON.parse(JSON.stringify({state,history}));assert.deepEqual(restored.state.growth,state.growth);assert.deepEqual(restored.history,history)});

test('all ten new species are reachable; each evolution uses its own candidates',()=>{const finals=new Set();for(const first of CREATURES.baby.next){assert.ok(CREATURES[first].next.length>1);for(const middle of CREATURES[first].next){assert.ok(CREATURES[middle].next.length>1);for(const last of CREATURES[middle].next){assert.ok(CREATURES[last]);finals.add(last)}}}assert.equal(finals.size,10)});
test('old companions and completed histories retain their identifiers after art update',()=>{for(const id of ['sky','leaf','cloud','moon','flower','spring']){const stage=['sky','leaf'].includes(id)?2:3;const g={...grown(230),character:id,stage};const n=advance(g,day(21),'old');assert.equal(n.stage,4);assert.ok(CREATURES[n.character]);}for(const id of ['mokumo','kazemo','yorune','hoshipuru','hanapyon','pokaron','shizukuma','mizune']){const g={...grown(230),character:id,stage:4,completedAt:day(21)};assert.equal(advance(g,day(30),'new').character,id);assert.ok(Number.isInteger(CREATURES[id].sprite));}});

test('shorter day limits preserve existing progress and completed companions',()=>{const old={...grown(150),stage:2,character:'sprout',path:[{stage:1,character:'baby',at:start},{stage:2,character:'sprout',at:day(7)}]};const before=structuredClone(old);const updated=advance(old,day(7),'existing');assert.equal(updated.stage,3);assert.equal(updated.startedAt,old.startedAt);assert.equal(updated.points,150);assert.deepEqual(updated.path.slice(0,2),old.path);assert.deepEqual(old,before);const final=advance(grown(230),day(11),'final');assert.equal(final.stage,4);assert.deepEqual(advance(final,day(12),'different'),final);});
